name: cloom_clock
description: Digital clock.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    git: 
      url: https://github.com/Airyzz/flutter_clock.git
      path: flutter_clock_helper
  cupertino_icons: ^1.0.6
  flare_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
  
  assets:
    - assets/
    - assets/dark/
    - assets/light/
